### ISSUE TITLE
Running problems on the Mac platform

### ISSUE THREAD

**Issue by aaronmack** [pablode/gatling#10]
* In usdview

```
export PYTHONPATH=/Users/usd-build/lib/python && export PATH=/Users/usd-build/bin:/Users/usd-build/lib:$PATH && usdview --renderer=Gatling /Users/gatling/cornell.usdc
```

`segmentation fault`  usdview --renderer=Gatling

* Standalone
```
/Users/gatling/cmake-build-relwithdebinfo/bin/gatling
`HdGatling plugin is not supported!`
```

Any help would be greatly appreciated.

Aaron

**Comment by pablode** [comment]
Hi Aaron. Unfortunately I can't determine what's wrong based on the first error message. So here's what I think you can try to get it to work:
- update the Vulkan SDK
- clone the repository again (to ensure that submodules use the correct upstreams)
- remove _CMakeCache.txt_ and execute CMake again, using the MDL SDK 2022
- clear the installed files (`rm -rf <USD_INSTALL_DIR>/plugin/usd/hdGatling*`)
- install the Release configuration

If it still doesn't work, the problem may be caused by MacOS's security features. The renderer tries to load the MDL SDK library dynamically, which's signature may have changed due to the update. In this case, I would expect such a window to pop up:

<img width="532" alt="gh_1" src="https://user-images.githubusercontent.com/3663466/191065088-2c6f636a-d9e2-40ab-a489-60492698b08b.png">

Is this the case? If so, you can press 'Cancel' and afterwards allow the library in the System Preferences -> Security & Privacy -> General (bottom) panel.

<img width="663" alt="gh_2" src="https://user-images.githubusercontent.com/3663466/191065115-185547e5-ce5d-44de-aaea-f662ab8afc54.png">

Regarding the standalone: the executable is based on USD/Hydra and therefore also needs the PYTHONPATH and PATH environment variables.

If it still fails with a SEGFAULT, could you please paste the output of `vulkaninfo` here within a \<details\> tag?

Thanks, Pablo

**Comment by aaronmack** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/43235864/192098673-bb943915-7894-478e-ae47-5b75fd25524c.png">

Seems to be a problem with my vulkan, I use the latest code to get the error.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/43235864/192098720-e2ff179b-0649-4e67-bf5c-78185a7fed78.png">

I'm still checking, any progress I'll let you know

**Comment by pablode** [comment]
Can't support macOS anymore since I've fully switched to hardware ray tracing. Let's hope supports lands in MoltenVK rather soon!
