### ISSUE TITLE
Can't compile against USD build provided by Nvidia

### ISSUE THREAD

**Issue by ryanknightley** [pablode/gatling#14]
Attempting to follow the instructions to the letter and have made some progress but when I go to compile the plugin and hdGatling I get errors that osdCPU.lib cannot be found. I compiled OpenSubdiv separately and dropped it into the location referenced but now get errors for LNK1104: cannot open file 'boost_python310-vc143-mt-x64-1_78.lib' [C:\Users\ryan\gatling\build\src\h
dGatling\hdGatling.vcxproj].

Is there a better practice for getting this to work?

**Comment by pablode** [comment]
Hi, unfortunately it usually requires manual work to link against foreign-built USD distributions due to baked paths (see pxrConfig.cmake) and environment differences (Python, compiler, compiler version).

I just tried out building against the lastest NVIDIA binaries (v24.08) and here are the changes I had to make:
1. add /bin, /lib to the PATH, set PYTHONPATH to /lib/python
2. remove the hardcoded paths in pxrConfig.cmake and specify -DMaterialX_DIR
3. copy lib/usd_pxOsd.lib to lib/osdCPU.lib
4. edit /include/boost-1_78/boost/config/auto_link.hpp:193 to be "vc142"
5. set PXR_MTLX_STDLIB_SEARCH_PATHS to /libraries

<img src="https://github.com/user-attachments/assets/7e827e87-fe5d-4bfb-bd66-306105468984" width=50% height=50% />

Cheers!

**Comment by ryanknightley** [comment]
Thanks for the instructions! So I downloaded the latest binaries and followed your instructions but get stuck at building the solution:

![image](https://github.com/user-attachments/assets/dfd8d56c-b541-403c-aaa7-62ca9693d798)

I tried commenting out the lines related to Vulcan to see what would happen and it just got caught on the next bit with SPIRV.

**Comment by pablode** [comment]
You need to clone recursively or run `git submodule update --init --recursive`

**Comment by ryanknightley** [comment]
Thank you! After doing that, I am able to build the solution. When I go to compile I receive 3 errors and quite a few warnings:

![image](https://github.com/user-attachments/assets/9383779a-6614-4f90-a9ed-254c9ccbefa4)

Which makes sense because:

![image](https://github.com/user-attachments/assets/f8518e0d-828e-4819-888c-6a4be60842e5)

This is all I have. No "-gd"

**Comment by pablode** [comment]
I think this means that you try to build the Debug config (or none). Try Release instead? Also see the README for installing the results to the right location

**Comment by ryanknightley** [comment]
I tried just building it in the same terminal with the commands you have in your readme instead of using VS and it compiled properly, I think. I still need to put together a scene to test with but the fact that it shows up in usdview and renders the default sphere and the kitchen scene is a good start. I still have questions about how to integrate this with Blender and tools like Quiltix but I think we can mark this as resolved and user error.
