### ISSUE TITLE
License for cgpu?

### ISSUE THREAD

**Issue by ib00** [pablode/gatling#5]
I like your minimalistic compute library (cgpu)
and would like to use it in some other personal projects.

Your current license is GPL. Is there any way
you could change the license to more permissive
(or dual license) for cgpu.h and cgpu.c?

**Comment by pablode** [comment]
Hi @ib00!

I don't recommend using cgpu for your projects because it's an _application-specific_ abstraction layer.
This means that it's incomplete in many ways and makes hard assumptions on HW and the calling application.

You'd be better off by writing your own layer or using a project like [V-EZ](https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ). Your layer could have the same name and the same structure. You could start small and evolve it as needed, just like I do.

**Comment by ib00** [comment]
Thanks!

Vulkan API is not for humans. It's complete insanity.

**Comment by pablode** [comment]
Yes, working with Vulkan unfortunately requires much time and effort.
